Repository Famec7/OpenSourceProject, pull requests merged in 2024-05, with the labels that each got.

#8 [#7] 윈도우 자동 빌드화 기능 추가
  .github/workflows/main.yml
Labels: enhancement

#10 [#9] Pull Request시 빌드 자동화 기능 구현
  .github/workflows/unity-build.yml
Labels: bug, enhancement

#5 [#4] 아이템 효과 및 데이터 관리 시스템
  Assets/Data/Item.meta
  Assets/Data/Item/TestItemData.asset
  Assets/Data/Item/TestItemData.asset.meta
  Assets/Prefabs.meta
  Assets/Prefabs/ItemTest.prefab
  Assets/Prefabs/ItemTest.prefab.meta
  Assets/Scenes/ItemTestScene.unity
  Assets/Scenes/ItemTestScene.unity.meta
  Assets/Scripts.meta
  Assets/Scripts/Item.meta
  Assets/Scripts/Item/ItemData.meta
  Assets/Scripts/Item/ItemData/ItemDataBase.cs
  Assets/Scripts/Item/ItemData/ItemDataBase.cs.meta
  Assets/Scripts/Item/ItemData/TestItemData.cs
  Assets/Scripts/Item/ItemData/TestItemData.cs.meta
  Assets/Scripts/Item/ItemEffect.meta
  Assets/Scripts/Item/ItemEffect/ItemEffectBase.cs
  Assets/Scripts/Item/ItemEffect/ItemEffectBase.cs.meta
  Assets/Scripts/Item/ItemEffect/TestItemEffect.cs
  Assets/Scripts/Item/ItemEffect/TestItemEffect.cs.meta
  Assets/Scripts/Item/ItemType.cs
  Assets/Scripts/Item/ItemType.cs.meta
  Assets/Scripts/Managers.meta
  Assets/Scripts/Managers/DataManager.cs
  Assets/Scripts/Managers/DataManager.cs.meta
  Assets/Scripts/Managers/GameManager.cs
  Assets/Scripts/Managers/GameManager.cs.meta
  Assets/Scripts/Managers/Singleton.cs
  Assets/Scripts/Managers/Singleton.cs.meta
  Assets/Scripts/Map.meta
  Assets/Scripts/Map/BackgroundScrolling.cs
  Assets/Scripts/Map/BackgroundScrolling.cs.meta
  Assets/Scripts/Player.meta
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerController.cs.meta
  Assets/Scripts/Player/PlayerData.cs
  Assets/Scripts/Player/PlayerData.cs.meta
  Assets/Scripts/Player/PlayerItemHandler.cs
  Assets/Scripts/Player/PlayerItemHandler.cs.meta
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/TagManager.asset
Labels: enhancement

#18 [#17] PlayerController.cs 주석 오류 해결
  Assets/Scripts/Player/PlayerController.cs
Labels: bug

#16 [#11] 장애물, 장애물 충돌 시스템 및 피격 시 무적 시스템 구현
  Assets/Images.meta
  Assets/Images/Obstacles.meta
  Assets/Images/Obstacles/blade_3.png
  Assets/Images/Obstacles/blade_3.png.meta
  Assets/Images/Obstacles/long_chain_piece.png
  Assets/Images/Obstacles/long_chain_piece.png.meta
  Assets/Images/Obstacles/med_post.png
  Assets/Images/Obstacles/med_post.png.meta
  Assets/Images/Obstacles/nut_over_top_over_wood.png
  Assets/Images/Obstacles/nut_over_top_over_wood.png.meta
  Assets/Images/Obstacles/spikes_1.png
  Assets/Images/Obstacles/spikes_1.png.meta
  Assets/Images/Obstacles/swinging_spike_block_2.png
  Assets/Images/Obstacles/swinging_spike_block_2.png.meta
  Assets/Prefabs/ObstacleBottom.prefab
  Assets/Prefabs/ObstacleBottom.prefab.meta
  Assets/Prefabs/ObstacleBottomDouble.prefab
  Assets/Prefabs/ObstacleBottomDouble.prefab.meta
  Assets/Prefabs/ObstacleTop.prefab
  Assets/Prefabs/ObstacleTop.prefab.meta
  Assets/Scenes/HitDetectionTest.unity
  Assets/Scenes/HitDetectionTest.unity.meta
  Assets/Scripts/Player/PlayerController.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/TagManager.asset
  UpgradeLog.htm
Labels: enhancement
